RequestApplication/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RequestApplication.Controllers
{
    public class InfoController : Controller
    {
        // GET: Info
        public ActionResult OurTeam()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
            return View();
        }

        public ActionResult News()
        {
            return View();
        }
    }
}

RequestApplication/Views/Shared/RequestListNotificationPartial.cshtml
<!DOCTYPE html>
<html>
<head>
    <link  rel="stylesheet" type="text/css" href="~/Content/NotificationStyle.css"/>
</head>
<body>
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content notificationsModal">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Notifications</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="listNotifications" class="list-group">

                    </div>
                </div>
                <div class="modal-footer">
                    <button id="buttonClose" type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    @if (User.IsInRole("company"))
    {
        <script src="~/Scripts/KSScripts/GetCompanyNotifications.js" type="text/javascript"></script>
        <script src="~/Scripts/KSScripts/ManageCompanyNotifications.js" type="text/javascript"></script>
    }
    else
    {
        <script src="~/Scripts/KSScripts/getNotifications.js" type="text/javascript"></script>
        <script src="~/Scripts/KSScripts/ManageNotifications.js" type="text/javascript"></script>
    }

</body>
</html>

RequestApplication/Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Request Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/HomePage.css")

    <!-- <link href="https://fonts.googleapis.com/css?family=montserrat:400,700" rel="stylesheet" type="text/css">
     <link href="https://fonts.googleapis.com/css?family=lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">  !-->
    <link rel="stylesheet" type="text/css" href="~/Content/NotificationStyle.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
</head>

<nav class="navbar navbar-expand-sm navbar-blue " style="background-color:black">

    <a class="navbar-brand" href="@Url.Action("Index", "Home")">
        <img class="rounded" src="~/Images/request_logo.png" alt="Logo" style="width:100px;">
    </a>

    <div class="navbar-collapse collapse justify-content-end">
        <ul class="navbar-nav ">

            <li class="nav-item">
                <a>@Html.Partial("_LoginPartial") </a>
            </li>
        </ul>
    </div>
</nav>

<div class="body">
    @RenderBody()
</div>
<footer class="page-footer text-center" style="background-color:#1a1a1a;">
    <div class="d-flex">
        

            <div class="flex-fill">

                <!-- Links -->
                <h5 class="text-uppercase" id="H5T">About</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="@Url.Action("OurTeam","Info")">Our Team</a>
                    </li>
                    <li>
                        <a href="@Url.Action("News","Info")">News</a>
                    </li>
                </ul>

            </div>

            <!-- Grid column -->
            <div class="flex-fill">

                <!-- Links -->
                <h5 class="text-uppercase" id="H5T">Customer Servise</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="@Url.Action("FAQ","Info")">FAQ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ContactUs","Info")">Contact Us</a>
                    </li>
                </ul>

            </div>
            <!-- Grid row -->

            <div class="flex-fill">

                <!-- Links -->
                <h5 class="text-uppercase" id="H5T">Community</h5>
                <ul class="list-unstyled list-inline">
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com">
                            <i class="fab fa-facebook"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://twitter.com">
                            <i class="fab fa-twitter"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://plus.google.com/discover">
                            <i class="fab fa-google-plus"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com">
                            <i class="fab fa-linkedin"> </i>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
   
</footer>
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)